version: '3'

volumes:
  static:
  pg_data:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    image: danyamikola78/foodgram_frontend
    command: cp -r /app/build/. /app/frontend_static/
    volumes:
      - static:/app/frontend_static
  backend:
    env_file: .env
    image: danyamikola78/foodgram_backend
    volumes:
      - static:/app/web
      - media:/app/media
    depends_on:
      - db 
  gateway:
    env_file: .env
    image: danyamikola78/foodgram_gateway
    volumes:
      - static:/web
      - media:/web/media
    ports:
      - 8000:80
    depends_on:
      - backend